exclude: "^.*ipynb$"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-builtin-literals
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
        args: ["--maxkb=10000"]
      - id: check-yaml
      - id: debug-statements
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        types: [python]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10
        types: [python]
        args: [--line-length=90]
  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        name: stricter_flake
        types: [python]
        files: components/
        args:
          - --max-line-length=90
          - --max-cognitive-complexity=15
          - --ignore=W503,ANN101,ANN102,ANN002,ANN003,ANN204, E203
          - --classmethod-decorators=classmethod,validator,root_validator
        additional_dependencies:
          - pep8-naming
          - flake8-builtins
          - flake8-comprehensions
          - flake8-bugbear
          - flake8-cognitive-complexity
          - flake8-annotations
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args:
          - --convention=google
          - --add-ignore=D100,D101,D102,D103,D104,D105,D106,D107,D415,D205
        files: components/
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        args:
          - --verbosity=2
        files: components/
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.1.2
    hooks:
      - id: prettier
        types: [python]
